var english = {
	"ld_home": "Prescription Homepage",
	"ld_prof":"Patient Profile",
	"ld_login":"Log in",
	"ld_logout":"Log out",
	"ld_user":"Patient NHC",
	"ld_pass":"Password",
	"ld_serv":"Server URL (optional)",
	"ld_servdef":"Public FHIR server by default",
	"ld_greet":"Hello,",
	"ld_visit":"Last visit date",
	"ld_doc":"Seen by Dr. ",
	"ld_notes":"Notes",
	"ld_break":"Breakfast",
	"ld_lunch":"Lunch",
	"ld_merienda":"Snack",
	"ld_dinner":"Dinner",
	"ld_sleep":"Bedtime",
	"ld_route":"Route",
	"ld_sched":"Schedule",
	"ld_w":"With",
	"ld_wo":"Without",
	"ld_food":"Food",
	"ld_submit":"Submit",
	"ld_meds":"Prescriptions",
	"ld_diags":"Conditions",
	"ld_alg":"Allergies",
	"ld_name":"Name",
	"ld_code":"Code",
	"ld_1rec":"First recorded",
	"ld_date":"Date",
	"ld_start":"Start",
	"ld_end":"End",
	"ld_fre":"Frequency",
	"ld_d":"Day",
	"ld_none":"None found",
	"ld_warndose":"see dosage instructions/ schedule",
	"ld_nav":"Menu",
	"ld_warnlogin":"No account found with those credentials on this server",
	"ld_warnserve":"Bad server address",
	"ld_warnpid":"Enter patient ID",
	"df_pill":"pill",
	"df_cap":"capsule",
	"df_eye":"drops",
	"df_inj":"injection",
	"df_pow":"powder",
	"df_inh":"inhalation"
};

var spanish = {
	"ld_home": "Recetas (inicio)",
	"ld_prof":"Perfil de paciente",
	"ld_login":"Entrar",
	"ld_logout":"Salir",
	"ld_user":"NHC de Paciente",
	"ld_pass":"Contraseña",
	"ld_serv":"Dirección de servidor (opcional)",
	"ld_servdef":"Servidor público de FHIR por omisión",
	"ld_greet":"Hola,",
	"ld_visit":"Fecha de última visita",
	"ld_doc":"Visto por Dr(a). ",
	"ld_notes":"Notas",
	"ld_break":"Desayuno",
	"ld_lunch":"Almuerzo",
	"ld_merienda":"Merienda",
	"ld_dinner":"Cena",
	"ld_sleep":"Al Acostarse",
	"ld_route":"Ruta",
	"ld_sched":"Horario",
	"ld_w":"Con",
	"ld_wo":"Sin",
	"ld_food":"Comida",
	"ld_submit":"Entregar",
	"ld_meds":"Fármacos dispensados",
	"ld_diags":"Enfermedades",
	"ld_alg":"Alergias",
	"ld_name":"Nombre",
	"ld_code":"Código",
	"ld_1rec":"Primera fecha",
	"ld_date":"Fecha",
	"ld_start":"Comienzo",
	"ld_end":"Fin",
	"ld_fre":"Frecuencia",
	"ld_d":"Día",
	"ld_none":"Nada encontrado",
	"ld_nav":"Menú",
	"ld_warndose":"lee las instrucciones/ el horario de dispensación",
	"ld_warnlogin":"No hay ninguna cuenta con esas credenciales en el servidor",
	"ld_warnserve":"Mala dirección de servidor",
	"ld_warnpid":"Incluye ID de paciente",
	"df_pill":"comprimido",
	"df_cap":"cápsula",
	"df_eye":"gotas",
	"df_inj":"injección",
	"df_pow":"pulverización",
	"df_inh":"inhalación"
};
